version: '3.8'

services:
   app-container:
      container_name: app-container
      build:
         context: .
         dockerfile: Dockerfile
      ports:
         - '8080:80'
      networks:
         - app-network
      depends_on:
         - db-container

   db-container:
      container_name: db-container
      image: mysql:5.7
      environment:
         MYSQL_ROOT_PASSWORD: rootpassword
         MYSQL_DATABASE: tododb
         MYSQL_USER: todouser
         MYSQL_PASSWORD: todopassword
      ports:
         - '3306:3306'
      volumes:
         - db_data:/var/lib/mysql
      networks:
         - app-network

   jenkins-container:
      container_name: jenkins-container
      build:
         context: .
         dockerfile: Dockerfile.jenkins
      ports:
         - '8081:8080'
      networks:
         - app-network
      volumes:
         - jenkins_data:/var/jenkins_home
         - /var/run/docker.sock:/var/run/docker.sock

networks:
   app-network:
      name: todo_list_app_network

volumes:
   db_data:
      name: todo_list_db_data
   jenkins_data:
      name: todo_list_jenkins_data
